### ISSUE TITLE
Skills that rely on canHurt may end up benefiting enemies

### ISSUE THREAD

**Issue by Mykindos** [Mykindos/BetterPvP#209]
Skills that provide allies buffs that check the relationship based on canHurt may end up buffing enemies if they are in a safe zone

Function to fetch nearby enemies / allies may need to be changed

LOW PRIORITY

**Comment by StudentAlleg** [comment]
FetchNearbyPropertyEvent is what populates the EntityProperty, which is done using canHurt. So all abilities that affect allies apply to all players that that player cannot hurt. Change would be to check for Clan in Clans (which iirc is done in the clansSkillListener)/ally instead of whether damage is allowed.

**Comment by Mykindos** [comment]
Fixed by https://github.com/Mykindos/BetterPvP/pull/250 I believe
