### ISSUE TITLE
Meridian Scepter

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#283]
- Needs a more robust LOS check to make sure the projectile doesn't go through thin blocks when the player is pressed against them
- Needs less incentive to base camp, maybe a maxFollowDuration that will remove the particle if it has been chasing a player for too long, or some other range inhibiting change
- To combat the longer range nerfs, could give it the ability to store charges that could be used subsequently

**Comment by braulio-dev** [comment]
If the Meridian Scepter does make it back into Clans, it'll most likely have a completely different format. I'd like to stay away from ranged legendaries as a whole to avoid the whole base camping dilemma, mostly because those are simply hit-or-miss features with difficult balancing opportunity.

**Comment by StudentAlleg** [comment]
I have 2 ideas for the scepter, because as much as I liked the old iteration it was problematic

1. shoot a single magic bullet. While holding down interact, the bullet will travel towards your crosshair (like SSM Wither Skeleton wither skull). When releasing, the bullet will continue its last vector. Has a very limited seek ability when released, will turn towards enemy players/mobs within 2 blocks.
2. Convert to a melee weapon. Hold interact to charge. Upon release, swing forward, dealing AoE magic (true) damage. Similar to SCP:SL Jailbird.
