### ISSUE TITLE
dying in combat sometimes makes you unsafe when you respawn

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#346]

**Comment by braulio-dev** [comment]
Also doesn't clear your damage log

**Comment by braulio-dev** [comment]
After looking over the code, it shouldn't be possible to actually be unsafe when respawning because the `lastDamage` is properly being reset, which is the variable used to detect when being unsafe. This only leaves us with the possibility of hits and some skills damaging players after they die, but this doesn't necessarily mean it's a problem with the combat system, but rather with some state managers like effect listeners, etc.

https://github.com/Mykindos/BetterPvP/blob/6e3473b4b38107c24a0988922d9f72b1d1a74784/core/src/main/java/me/mykindos/betterpvp/core/combat/death/DeathListener.java#L46C43-L46C43

**Comment by braulio-dev** [comment]
After looking over the code, it shouldn't be possible to actually be unsafe when respawning because the `lastDamage` is properly being reset, which is the variable used to detect when being unsafe. This only leaves us with the possibility of hits and some skills damaging players after they die, but this doesn't necessarily mean it's a problem with the combat system, but rather with some state managers like effect listeners, etc.

https://github.com/Mykindos/BetterPvP/blob/6e3473b4b38107c24a0988922d9f72b1d1a74784/core/src/main/java/me/mykindos/betterpvp/core/combat/death/DeathListener.java#L45-L47

I'm going to go ahead and mark this as a wont-fix because there's a bigger underlying issue that needs to be resolved.
