### ISSUE TITLE
rework inferno per ci siggestions

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#409]

**Comment by ezrn** [comment]
I will do this

**Comment by StudentAlleg** [comment]
https://discord.com/channels/161738857136521217/1195566288332918824/1195566288332918824
Armadaeiel
>Perceived issue: Inferno is viable, but generally unsatisfying to use. I believe this to be for three major reasons. 
It mechanically functions fairly blandly, right click and aim to have a fairly non-interactive interaction between the user and recipient.
It resembles blizzard very heavily, only the end result largely changing.
It relies on magma blade fairly heavily to be viable in many situations, and abilities should all be fairly self sufficient barring some. (Admittedly, for example magma blade DOES pretty explicitly rely on fire based mage abilities to be viable but this is likely unavoidable without doing a rework on magma blade as well.)

All of these reasons that I see cause the ability to feel fairly lame in the hands of a new player, and only marginally interesting in the hands of someone experienced using magma blade. Each ability should feel unique and impactful, and currently I see it as failing in both categories. I understand that the ability IS unique and impactful, but it could be changed to actually feel the part.

Purpose: This rework aims to address satisfaction primarily (giving it more oomf), while keeping its combos (namely magma blade) but mechanically making it function differently.

Basic rework idea: Inferno will no longer be a machine gun ability, and instead a charged burst of flame. Letting go of right click throws out a burst of flame in a shotgun-like cone in front of the user. The higher the charge, the more flames (more damage) and larger range (bigger cone). Due to being a shotgun, it will also have a heavy damage falloff however it should still light people on fire for a little bit.

I think it should have a very low cooldown, but not 0. Something like 1 second, basically so you can use it to do low damage shots to proc magma blade.

Why I think this solves the listed issues: Due to the mechanical change it would no longer even slightly resemble blizzard. This would help kit diversity greatly. 

On top of this, it would be more capable of having cosmetic oomf behind it due to actually having a cooldown. Firey bursts of sound, and possibly heavier visuals because it wouldn't be active constantly. 

Lastly, due to it still having a low cooldown, it would still be viable to use with magma blade as a combo tool. While you wouldn't proc magma blade every hit, it would be more self sufficient damage-wise and not rely on magma blade to be viable while still being a strong synergy.
