### ISSUE TITLE
Void needs to reduce every based on damage not based on hits

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#538]

**Comment by Polisvh** [comment]
So generally the issue is that right now void drains 15 energy per hit, no matter what the damage was (you can get rid of void in 5 hits with fist where no real damage was even reduced, and get rid of void instantly with 1 hit of inferno).
On mineplex - void drained additional (I dont remember the exact number but I think it was 4) 4 mana per 1 damage reduced.
