### ISSUE TITLE
Some suggestions and potential issues from my observation

### ISSUE THREAD

**Issue by Polisvh** [Mykindos/BetterPvP#645]
Disable swim

Overwhelm deals 0 bonus damage - this value was originally set to 0.25
vengeance - it is greatly buffed compared to mineplex on which it already was one of best abilities for knight (Mineplex GI planned to highly nerf it!)

On mineplex vengeance worked this way:
When you attack someone, your damage is increased by 0.5/1/1.5 for each time the enemy hurt you since you last hit them, up to a maximum of 1/2/3 bonus damage 

On here it is increased by 1/2/3 damage with 2/3/4 dmg cap which means you always deal +3 damage when trading hits which is insanly good - you buffed it to be twice as good than it used to be, it needs rescalling and I suggest 0.75/1.25/1.75 damage bonus for maximum of 1.5/2.5/3.5 but also add feature that the bonus expires after certain time of not getting hit like 6 seconds. Also I don't know if this is an issue to you but mineplex GI stated that the bonus damage should only be applied to players who actually hit you

Sharpshooter change makes precision useless honestly, I recommend adding back the "bonus resets if 2 shots are missed" like it used to be on mineplex 

All Swarm levels arent different from one another, either remove the ability or add some more use to it (I recommend making it work like SSM bat wave ability from Witch - very useful)

**Comment by ezrn** [comment]
You need to separate these into different issues because it's a pain to work with otherwise. Damage numbers are subject to change of course via testing and the correct ones will be found when the time times. I think overwhelm was just changed actually. There are also abilities that will probably get removed so wouldn't worry about some of those, for instance, I believe swim is already planned. A lot of what you suggested is also already in the game so I'm not sure what version you've been playing.
