### ISSUE TITLE
Honey Bottles 

### ISSUE THREAD

**Issue by RockyMichael** [Mykindos/BetterPvP#661]
Give Honey Bottles Functionality - Replenishes 50% of your Energy Bar. 20 Second Cooldown. Available in Shops.

**Comment by ezrn** [comment]
This exists already in energy apples, though unsure if those are staying. I do like the honey bottles better aesthetic wise, though would probably have to give them the mushroom stew treatment by retexturing them to allow stacking. I also like the 50% energy instead of a set amount of energy because it would increase the effectiveness of a skill like mana pool if that is added in the future

**Comment by braulio-dev** [comment]
Should probably replace energy apples with honey bottles and rename them to something more indicative of the effect

**Comment by RockyMichael** [comment]
Perhaps Energy Elixir?
