### ISSUE TITLE
Channeling abilities bug

### ISSUE THREAD

**Issue by ImMuscleMan** [Mykindos/BetterPvP#675]
Currently you can spam right click and left click whilst chanelling and keep chanelling whilst hitting entities (see attached video)

https://github.com/Mykindos/BetterPvP/assets/95445240/32804b65-308a-4e43-9851-926208e86588

**Comment by ezrn** [comment]
Very likely because you have a shield(wont be in the final version), though if the problem persists we could use a playerInteractEvent and listen for a left click to cancel the channel. Won't be able to stop the unblocking for less than a tick, but at that point it shouldn't matter if you cant perform any actions during it.

**Comment by StudentAlleg** [comment]
Cannot replicate with sword blocking, can with shields.

Seems to be solved with sword blocking.

**Comment by braulio-dev** [comment]
With our private sword blocking module this should be fixed with swords only. Legendaries would still have the same issue.

**Comment by StudentAlleg** [comment]
When using blizzard, it use the initial cost twice
