### ISSUE TITLE
In text commands that have pages, have clickable pages

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#761]
Add Next Page, previous page, and clickable last page for the number

Probably should create a framework to easily make/modify commands that use pages

**Comment by braulio-dev** [comment]
Most text commands should be moved to an inventory UI anyway so we should probably migrate them instead of making a whole framework for a text pagination system. This would also require signed messages as far as I know to edit sent messages to players, because we're definitely not going to be re-sending new messages each time a player presses next/previous page button.

**Comment by StudentAlleg** [comment]
> Most text commands should be moved to an inventory UI anyway so we should probably migrate them instead of making a whole framework for a text pagination system. This would also require signed messages as far as I know to edit sent messages to players, because we're definitely not going to be re-sending new messages each time a player presses next/previous page button.

Agreed
